scrape_configs:
  - job_name: 'NHK easy api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'NHK easy api'
